### PR TITLE
threads.go: wraps threads initialization in init()

### PR DESCRIPTION
**Pull request by runcom**
I'll reintroduce it whenever it's needed (given it will)

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

### CODE REVIEW

**Comment by shanemhansen** [comment]
So from my reading of the openssl docs, this code is required to get thread safety. I believe something similar is done in pyopenssl.

https://github.com/msabramo/pyOpenSSL/blob/master/OpenSSL/crypto/crypto.c#L779

https://www.openssl.org/docs/manmaster/crypto/threads.html

**Comment by runcom** [comment]
my bad, I totally overlooked the fact that it was called globally, I have to call it in an `init()` function instead. Thanks

**Comment by runcom** [comment]
@shanemhansen updated

**Comment by runcom** [comment]
ping @shanemhansen

**Pull request merged**
