### PR TITLE
*: fix merges

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@linux.com>

### CODE REVIEW

**Comment by runcom** [comment]
@shanemhansen fixing a bunch of errors
this is in WIP, can I have a label for WIP pull request? :)

**Comment by runcom** [comment]
tests are running fine now so feel free to merge this PR now :)
vet is working fine

**Comment by shanemhansen** [comment]
Label Added.  LGTM.

**Comment by runcom** [comment]
@shanemhansen guess I cannot apply label though lol

**Comment by shanemhansen** [comment]
I've granted you push access to the repository. I'll try and write up a document later, but for now just get a LGTM from me or @vbatts before you merge.

**Comment by runcom** [comment]
roger that

**Pull request merged**
