### PR TITLE
add x509/http pkg and rework

### PR DESCRIPTION
**Pull request by runcom**
add a new `x509` pkg following Go's api as usual
add `http` pkg with a dummy OpenSSL `RoundTripper`

Fix https://github.com/shanemhansen/gossl/issues/16

/cc @vbatts 

Signed-off-by: Antonio Murdaca <runcom@linux.com>

### CODE REVIEW

**Comment by runcom** [comment]
reworked the repo a bit to have `crypto/` and `http` where I'm currently working

**Comment by vbatts** [comment]
still failing on that weird `rand` compile issue

**Comment by runcom** [comment]
:( couldn't found the issue there yet, still digging, I have a bunch of local changes I should push here though

**Comment by runcom** [comment]
@vbatts @shanemhansen can we merge this as is for now since I'm already importing it in docker to back it up with openssl and the diff is becoming pretty big? No broken changes has been made here, it's just a clean setup following go's crypto pkg

**Comment by runcom** [comment]
I'm still researching the failures in tests tho

**Comment by runcom** [comment]
Bug should be fixed now -- pls Travis -- so I'd say this is good to go now :)

**Comment by runcom** [comment]
alright fixed! :tada:

**Comment by shanemhansen** [comment]
w00t!

**Pull request merged**
